export const AUTH_STATE_CHANGED = 'AUTH_STATE_CHANGED';
export const LOGOUT = 'LOGOUT';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const DIALOG = 'DIALOG';
export const SNACKBAR = 'SNACKBAR';
export const SILENT = 'SILENT'
export const NETWORK_ERROR = 'Network Error';
export const SERVICE_UNAVAILABLE = 'Service Unavailable';